version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - main_network
  postgres:
    image: 'postgres:15'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    networks:
      - main_network
volumes:
  postgres_data:

networks:
  main_network:
    external: true
