version: '3.8'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ./:/home/pptruser/app
      - /home/pptruser/app/node_modules
      - /home/pptruser/app/.next
    networks:
      - main_network
    command: [ "yarn", "dev" ]
  bot:
    restart: always
    depends_on:
      - web
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '1337:1337'
    volumes:
      - ./:/home/pptruser/app
    command: [ "yarn", "dev:bot" ]
    networks:
      - main_network
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    networks:
      - main_network
volumes:
  postgres_data:

networks:
  main_network:
    external: true
